# Generated by Django 5.1.7 on 2025-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.IntegerField()),
                ('password', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
